### ISSUE TITLE
Nothing is displayed in browser when running `gulp watch`

### ISSUE THREAD

**Issue by rtorino** [jeffling/angular-webpack-example#5]
I fired `gulp watch` and hit `localhost:8888` in browser but nothing is displayed. Before I did this, I added some static HTML elements just to make sure `index.html` is served with contents from the target directory. Maybe I just misunderstood the usage of fb-flo, please help. Thanks.

**Comment by jeffling** [comment]
Hey, sorry for the delay @rtorino. I'll watch the repo so I can respond faster.

 fb-flo doesn't actually serve the files. The chrome extension connects to the port and auto-refreshes css and auto-reloads the browser when you make html/javascript changes. 

Let me know if you have any more questions.
